virtual-vgo/vvgo

- .github/workflows/docker.yml
- Dockerfile
Implements the "build" stage of #15.
> Setup automated builds using Github Actions

- Dockerfile
- test/code_hygiene_test.go
* Adds some code hygiene tests
* Adds a test target to the docker file
```
docker build . --target vvgo --label vvgo
docker run -p8080:800 vvgo
```
```
docker build . --target tester --label vvgo-testing
docker run vvgo-testing
```
> add test target to dockerfile

- api_server.go
- api_server_test.go
Forgot to set the WWW-Authenticate header on the response for basic auth.
> tell the browser we want auth

- .github/workflows/build.yml
- Dockerfile
- Makefile
- README.md
Possibly the laziest makefile ever written
> Add Makefile

- cmd/vvgo/main.go
- cmd/vvgo/main_test.go
- pkg/api/auth.go
- pkg/api/parts.go
- pkg/api/parts_test.go
- pkg/api/server.go
- pkg/api/testdata/parts.html
- pkg/api/upload.go
- pkg/api/upload_test.go
- public/css/parts.css
- public/parts.gohtml
Most importantly, bucket names are now environment configs. :)
> bunch of small fixups

- pkg/api/server.go
- pkg/api/testdata/index.html
- pkg/api/testdata/parts.html
- pkg/api/views.go
- pkg/api/views_test.go
- public/css/theme.css
- public/navbar.gohtml
* Hides the link for /parts unless logged in
* Still using basic auth, so we get auth details from http headers
> hide link behind login

- pkg/api/helpers.go
- pkg/api/testdata/parts.html
- pkg/api/testdata/parts.json
- pkg/api/views.go
- pkg/api/views_test.go
- pkg/projects/projects.go
* Disable snake eater from the parts page. (We can re-enable it for certain auth tokens later).
* Update tests to make sure disabled parts are actually disabled.
> Disable snake eater

- pkg/api/testdata/parts.html
- pkg/api/views.go
- pkg/projects/projects.go
- public/parts.gohtml
; add reference track for monster hunter
> rename backing-track to reference-track

- pkg/api/testdata/parts.html
- public/js/parts.js
- public/parts.gohtml
Adds a few ui cleanups and adds page info
> Sort alpha

- pkg/discord/discord.go
- pkg/discord/discord_test.go
- pkg/tracing/tracing.go
- pkg/tracing/tracing_test.go
This does not include the controller authorization code from https://github.com/virtual-vgo/vvgo/pull/106. This only has the code bits for talking to discord.
> add discord client code

- pkg/api/testdata/backups.html
- pkg/api/testdata/index.html
- pkg/api/testdata/parts.html
- public/backups.gohtml
- public/css/parts.css
- public/header.gohtml
- public/index.gohtml
- public/parts.gohtml
I was mostly using the relative paths as a hack to make my ide work. But I figured out how to make it work with the absolute paths, and I think that's preferred in most cases.
> Html Src from root

- pkg/api/auth.go
- pkg/api/backups.go
- pkg/api/helpers.go
- pkg/api/testdata/backups.html
- pkg/api/testdata/index.html
- pkg/api/testdata/parts.html
- pkg/api/views.go
- pkg/api/views_test.go
- public/backups.gohtml
- public/css/index.css
- public/css/parts.css
- public/css/theme.css
- public/footer.gohtml
- public/index.gohtml
- public/navbar.gohtml
- public/parts.gohtml
Cleanup for the navbar
Adds footer
Changes some colors
> Navbar cleanup

- public/hello.html
> Revert "Delete hello.html"

- pkg/api/backups.go
- pkg/api/backups_test.go
- pkg/api/testdata/backups.html
- public/backups.gohtml
This allows you to upload and restore from a backup file on your local machine.
> add restore from file option

- public/css/theme.css
Adds bg-facebook-blue color CSS to PR #186
> Add bg-facebook-blue css

- .gitignore
- cmd/vvgo/main.go
- cmd/vvgo/main_test.go
- cmd/vvgo/testdata/config.json
- pkg/api/login.go
- pkg/api/server.go
- pkg/api/server_test.go
- pkg/discord/discord.go
- pkg/discord/discord_test.go
- pkg/redis/redis.go
Use a config file instead of environment vars for configuration
> Config file

- public/parts.gohtml
> Updated submission link in parts.gohtml

- public/parts.gohtml
For the credits for "Credits Roll"!
> ENCORE addition :)

- public/js/parts.js
Dunno if this actually works lol
> Sort by Project first, then by Score Order

- pkg/api/auth_test.go
- pkg/api/index.go
- pkg/api/login.go
- pkg/api/login_test.go
- pkg/api/parts.go
- pkg/api/server.go
- pkg/api/server_test.go
- pkg/login/access.go
- public/parts.gohtml
gets rid of vvgo-uploader and vvgo-admin roles
adds roles for vvgo-teams and vvgo-leader
Discord login handler will check for these roles when you login
Updates views with unreleased projects for teams and admin roles
> add more roles and give teams more visibility

- pkg/api/testdata/index.html
- public/css/index.css
- public/index.gohtml
> dont include index.css

- public/archive/index.gohtml
- public/archive/project.gohtml
Dont show parts on the archive pages
Remove links for projects without videos
> couple of cleanups for the archive index

- public/archive/project.gohtml
Used card-columns baybeeeeeee
They said it couldn't be done but I done did it with just one Google search
> Prettier Project Pages

- pkg/api/archive.go
- pkg/api/index.go
- pkg/api/login.go
- pkg/api/parts.go
- pkg/api/testdata/index.html
- pkg/api/testdata/login.html
- pkg/login/access.go
- public/footer.gohtml
Adds some useful info for vvgo teams to the bottom of website pages.
> add dev info to footer on views

- public/index.gohtml
please please please please please please please please please please please please please please please please please please please please please please please please
> Capitalized Discord, edited to be less pleading

- pkg/sheets/parts.go
- pkg/sheets/parts_test.go
- public/parts.gohtml
Tweaking alignments n such on parts page. Also fixing reference track and moving it to top.
> Parts tweaks

- scoreOrder.md
> Update scoreOrder.md yet again

- ui/src/components/mixtape/NewProjectWorkflow.tsx
- ui/src/components/shared/FancyProjectMenu.tsx
It aint beautiful but it gets the job done
> patch in easier way to do edits

- .eslintrc.js
- .github/workflows/test.yml
- .gitignore
- .mocharc.js
- package-lock.json
- package.json
- tsconfig.json
- ui/src/components/Home.tsx
- ui/src/components/Projects.tsx
- ui/src/datasets/ApiError.test.ts
- ui/src/datasets/ApiError.ts
- ui/src/datasets/ApiResponse.ts
- ui/src/datasets/Credit.test.ts
- ui/src/datasets/CreditsPasta.test.ts
- ui/src/datasets/CreditsPasta.ts
- ui/src/datasets/CreditsTable.test.ts
- ui/src/datasets/Dataset.test.ts
- ui/src/datasets/Dataset.ts
- ui/src/datasets/Director.test.ts
- ui/src/datasets/GuildMember.test.ts
- ui/src/datasets/GuildMember.ts
- ui/src/datasets/Highlight.test.ts
- ui/src/datasets/MixtapeProject.test.ts
- ui/src/datasets/MixtapeProject.ts
- ui/src/datasets/OAuthRedirect.test.ts
- ui/src/datasets/hooks.ts
> Test UI 😍 

- src/components/shared/Navbar.tsx
Updated Navbar to say "Mixtape"
> Mixtape 3 Naming Fixes

- src/components/login/LoginFailure.tsx
- src/components/shared/Footer.tsx
- src/data/discord.ts
Changed some bad discord links
https://discord.gg/vvgo ---> https://discord.gg/mt8EZdsrc6
> Fix Bad Discord Links
